name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  TURBO_TELEMETRY_DISABLED: '1'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: ./.github/actions/setup

      - run: pnpm --filter @repo/prisma run generate
      - run: pnpm turbo run build
      - run: pnpm turbo run test
